import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import myPhoto from "../public/myPhoto.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";

import { useState } from "react";

import draw from "../public/draw.png"
import imageGallery from "../public/imageGallery.png";

import CookingBlog from "../public/cooking_blog.png";
import CookingBlog2 from "../public/cooking_blog2.png";
import gradP1 from "../public/gradP1.png";
import gradP2 from "../public/gradP2.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mohamed Medhat Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons dark:text-white">
              MOHAMED MEDHAT
            </h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8 "
                  href="https://docs.google.com/document/d/1qlkNLOYD-U0hpD2StlbPxN5FITNqNJkj/edit?usp=sharing&ouid=117336269782074297516&rtpof=true&sd=true"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl ">
              Mohamed Medhat
            </h2>
            <h3 className=" text-2xl py-2 md:text-3xl dark:text-white">
              FullStack Developer.
            </h3>
            <p className=" text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto  dark:text-gray-400">
              Full Stack developer using MERN Stack, Grad year collage student
              in the faculty of engineering at tanta university, specialized in
              computer science and automatic control.
            </p>
          </div>

          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a
              href="https://www.linkedin.com/in/mohamed-medhat-337b811b8/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="https://github.com/mohamed20medhat"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub />
            </a>

            <a
              href="https://www.youtube.com/channel/UCcnaeaZrr2lA2g3JI3O4CXg"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillYoutube />
            </a>
          </div>

          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 ">
            <Image
              src={myPhoto}
              alt="my photo"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I have started my learning journey since the second year in
              collage. so it has been 2 years now. I have learnt through online
              courses and made tons of small to medium sized projects. I
              understand that I am at the beginning of my journey and there is A
              LOT more to learn and I am willing to put the time and effort.
            </p>
          </div>

          <div className=" lg:flex gap-10 dark:text-white">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-700">
              <Image src={design} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2">UI/UX</h3>
              <p className="py-2 ">
                I have experience in building user interfaces that provide good
                user experience.
              </p>
              <h4 className="py-4 text-teal-600  dark:text-teal-200">
                Design tools I use
              </h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Canva</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-700">
              <Image src={code} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2">Coding</h3>
              <p className="py-2 ">
                2 years of experience building web applications for my collage
                that are bushiness oriented. I always search and learn how the
                bushiness works before I start implementing.
              </p>
              <h4 className="py-4 text-teal-600  dark:text-teal-200">
                Frameworks and tools
              </h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                React JS || Html & JS || python
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                CSS || SCSS || Bootstrap || TailwindCSS{" "}
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Node JS || GO lang || Flask
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Mongo DB || MySQL
              </p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-700">
              <Image src={consulting} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2">Projects</h3>
              <p className="py-2 ">
                Projects that I made during the past 2 years of learning
              </p>
              <h4 className="py-4 text-teal-600  dark:text-teal-200">
                Things that I built before
              </h4>
              <p className="text-teal-900 py-1 dark:text-teal-400">
                <a href="https://github.com/mohamed20medhat/Flask_Projects">
                  Flask&MySQL : health insurance company + Blog
                </a>
              </p>
              <p className="text-teal-900 py-1 dark:text-teal-400">
                <a href="https://github.com/mohamed20medhat/mybrary">
                  Node JS : Library
                </a>
              </p>
              <p className="text-teal-900 py-1 dark:text-teal-400">
                <a href="https://github.com/mohamed20medhat/ecommerce_SE">
                  Node JS : ECommerce
                </a>
              </p>
              <p className="text-teal-900 py-1 dark:text-teal-400">
                <a href="https://github.com/mohamed20medhat/influencerBlog">
                  Node JS : Cooking Blog
                </a>
              </p>
              <p className="text-teal-900 py-1 dark:text-teal-400">
                <a href="https://github.com/mohamed20medhat/todo_App_React">
                  React js: TO DO app
                </a>
              </p>
              <p className="text-teal-900 py-1 dark:text-teal-400">
                <a href="https://github.com/mohamed20medhat/react-image-gallary">
                  React JS : Image Gallery
                </a>
              </p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-200">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I can build full stack web applications using
              <span className=" text-teal-500 "> Node js and React js </span>
              Also I have experience in teaching how to build full stack
              projects to collage students.
            </p>
          </div>

          <div className=" flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className=" basis-1/3 flex-1">
              <Image
                src={CookingBlog}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={CookingBlog2}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={gradP1}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={gradP2}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={imageGallery}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={draw}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
