import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillYoutube,
  AiFillFacebook,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import mod from "../public/mod.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mohamed Medhat Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons dark:text-white">
              MOHAMED MEDHAT
            </h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8 "
                  href="https://www.linkedin.com/in/mohamed-medhat-337b811b8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl ">
              Mohamed Medhat
            </h2>
            <h3 className=" text-2xl py-2 md:text-3xl dark:text-white">
              FullStack Developer.
            </h3>
            <p className=" text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto  dark:text-gray-400">
              Full Stack developer W. MERN Stack and Grad year collage student
              in the faculty of engineering at tanta university, specialized in
              computers and automatic control.
            </p>
          </div>

          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a
              href="https://www.linkedin.com/in/mohamed-medhat-337b811b8/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="https://github.com/mohamed20medhat"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub />
            </a>

            <a
              href="https://www.youtube.com/channel/UCcnaeaZrr2lA2g3JI3O4CXg"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillYoutube />
            </a>
          </div>

          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 ">
            <Image src={mod} alt="3d image" layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I build full stack web applications for businesses using
              <span className=" text-teal-500 "> Node js and React js </span>
              And I can also build collage projects for cs students that are
              related to web development. I offer wide range of services
              including programming and teaching.
            </p>
          </div>

          <div className=" lg:flex gap-10 dark:text-white">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-700">
              <Image src={design} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Photo Shop
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Canva</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-700">
              <Image src={code} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                High Quality CODE
              </h3>
              <p className="py-2 ">
                Creating high quality code following best practices to make high
                quality and performance applications that satisfy your bushiness
                needs .
              </p>
              <h4 className="py-4 text-teal-600">Technologies That I Use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                React JS || Html & JS
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Node JS || GO lang
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Mongo DB || MySQL
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                CSS || SCSS || Bootstrap || TailwindCSS{" "}
              </p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-700">
              <Image src={consulting} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <p className="py-2 ">
                1 year of experience in building applications for bushiness. We
                will talk together and discuss your bushiness needs and provide
                the suitable solution.
              </p>
              <h4 className="py-4 text-teal-600">
                Fields That I worked With Before
              </h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Online Shop
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Blogs and Blogging
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Shops system && pharmacies
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Hospitals</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-200">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I build full stack web applications for businesses using
              <span className=" text-teal-500 "> Node js and React js </span>
              And I can also build collage projects for cs students that are
              related to web development
            </p>
          </div>

          <div className=" flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className=" basis-1/3 flex-1">
              <Image
                src={web1}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web2}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web3}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web4}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web5}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web6}
                alt="web"
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
